//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazy.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LazyEntities : DbContext
    {
        public LazyEntities()
            : base("name=LazyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Bug> Bugs { get; set; }
        public virtual DbSet<Fix> Fixes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Workspace> Workspaces { get; set; }
    }
}
